spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easy_mybatis?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

x: 1  #ip限制分钟
y: 100 #ip限制次数
sendEmail: 771407794@qq.com
